name: Python package

on:
  push:
    branches: [ master ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install faiss
      run: |
        pip install faiss-cpu
    - name: Test with pytest
      run: |
        python labml_nn/graphs/gat/experiment.py
