name: Python package

on:
  push:
    branches: [ master ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        source $HOME/miniconda/bin/activate
        conda init bash
        source ~/.bashrc
        conda create -n myenv python=3.9 -y
    - name: Install dependencies
      run: |
        source $HOME/miniconda/bin/activate myenv
        conda install -c conda-forge faiss-cpu -y
        pip install -r requirements.txt
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd):${PYTHONPATH}" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        source $HOME/miniconda/bin/activate myenv
        python labml_nn/graphs/gat/experiment.py
